FROM node:lts-buster as deps 
WORKDIR /deps
COPY package.json  .
RUN yarn install --ignore-scripts

FROM node:lts-buster as runner 
WORKDIR /home/node/code
USER node
COPY --from=deps --chown=node:node /deps/node_modules ./node_modules
COPY --chown=node:node . .
RUN yarn build